apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # labels for deployment. These can be different from pod labels and selector. These are just for deployment identification
  labels:
    project: roboshop-helm
    environment: dev
spec:
  replicas: {{ .Values.deployment.replicaCount}}
  # selector to identify pods managed by deployment
  selector:
    matchLabels:
      project: roboshop-helm
      environment: dev
  template:
    metadata:
      # pod template labels. Should match selector
      labels:
        project: roboshop-helm
        environment: dev
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}"  # nginx:latest