apiVersion: v1
kind: Service
metadata:
  name: service-demo
spec:
    type: {{ Values.service.type }}
  selector:
    project: roboshop
    environment: dev
  ports:
  - protocol: TCP
    port: 80   # Service Port
    targetPort: 80  # Pod Container Port
    nodePort: {{ Values.service.nodePort }}